# Generated by Django 3.0.6 on 2020-05-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='', upload_to='cars'),
            preserve_default=False,
        ),
    ]
